### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by Gnindit** [sqmk/huejay#115]
Hi
I am getting log full of these sometimes.

(node:11270) UnhandledPromiseRejectionWarning: Error: Huejay: socket hang up
at getHttpClient.request.then.catch.error (/home/pi/.node-red/node_modules/huejay/lib/Transport.js:106:15)
at process._tickCallback (internal/process/next_tick.js:68:7)
(node:11270) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 282)
(node:11270) UnhandledPromiseRejectionWarning: Error: Huejay: socket hang up
at getHttpClient.request.then.catch.error (/home/pi/.node-red/node_modules/huejay/lib/Transport.js:106:15)
at process._tickCallback (internal/process/next_tick.js:68:7)

nodejs v10.16.3
Node-red 0.20.7

**Comment by fvhemert** [comment]
+1 subscribing to get updates

**Comment by Travelbacon** [comment]
Please see https://github.com/Foddy/node-red-contrib-huemagic/issues/106 for more details.
More people added details of when it happens and when.
