### ISSUE TITLE
What does the following error mean? `Huejay: Failed to get results from meethue`

### ISSUE THREAD

**Issue by Wizek** [sqmk/huejay#119]
```
An error occurred: Huejay: Failed to get results from meethue Error: Huejay: Failed to get results from meethue
    at httpRequest.then.catch.response (C:\Users\Wizek\sandbox\exp-node-hue-2\node_modules\huejay\lib\DiscoveryStrategy\Nupnp.js:43:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by Wizek** [comment]
Nevermind, I was able to fix it by upgrading from 1.8.5 to 1.9.0
